# -*- coding: utf-8 -*-
"""inf211-wandji-miranda-24G2216.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zncZ_PO3pYYFaBRYudQyQ9kpQUO5v-PS
"""

# ==========================================
#   Nom et prenoms: WANDJI MIRANDA BRUNELLE
#   Matricule: 24G2216
# ==========================================

# ============================================================
#  Script complet : Récupération et analyse de commentaires YouTube avec Gemini
# ============================================================

# =========================
#  Installation des dépendances (spécial Google Colab)
# =========================
!pip install --upgrade google-api-python-client google-generativeai

# =========================
# Importation des bibliothèques
# =========================
import googleapiclient.discovery
import googleapiclient.errors
import google.generativeai as genai 
from urllib.parse import urlparse, parse_qs

# =========================
#  Configuration des clés API
# =========================

#  Remplace par tes propres clés API
YOUTUBE_API_KEY = "AQ.Ab8RN6KIqEDNjFS1AO4jb7gRuiz2a6Z5aHT0kJdTgIaF4skrmg"
GEMINI_API_KEY =  "AIzaSyB-vA6399UpYiN4seziAlupuALeZyVN1d8"
# Vérification simple
if YOUTUBE_API_KEY.startswith("TA_") or GEMINI_API_KEY.startswith("TA_"):
    print("❌ Attention : vous devez remplacer les clés API par vos vraies clés.")
else:
    print("✅ Clés API configurées correctement.")

# Configurer Gemini
genai.configure(api_key=GEMINI_API_KEY)

# =========================
# 📌 Extraction de l'ID vidéo depuis une URL
# =========================
def extract_video_id(youtube_url):
    """
    Extrait l'ID d'une vidéo YouTube à partir du lien complet.
    """
    try:
        parsed_url = urlparse(youtube_url)
        if parsed_url.hostname in ['www.youtube.com', 'youtube.com']:
            query = parse_qs(parsed_url.query)
            return query.get('v', [None])[0]
        elif parsed_url.hostname == 'youtu.be':
            return parsed_url.path[1:]
        else:
            return None
    except Exception as e:
        print(f"Erreur lors de l'extraction de l'ID : {e}")
        return None

# =========================
#  Récupération des commentaires YouTube
# =========================
def get_video_comments(api_key, video_id, max_comments=200):
    youtube = googleapiclient.discovery.build("youtube", "v3", developerKey=api_key)

    comments = []
    try:
        request = youtube.commentThreads().list(
            part="snippet",
            videoId=video_id,
            maxResults=100,
            textFormat="plainText"
        )
        response = request.execute()

        while response and len(comments) < max_comments:
            for item in response['items']:
                comment = item['snippet']['topLevelComment']['snippet']
                comments.append(comment['textDisplay'])

                if len(comments) >= max_comments:
                    break

            if 'nextPageToken' in response and len(comments) < max_comments:
                request = youtube.commentThreads().list(
                    part="snippet",
                    videoId=video_id,
                    pageToken=response['nextPageToken'],
                    maxResults=100,
                    textFormat="plainText"
                )
                response = request.execute()
            else:
                break

        return comments

    except googleapiclient.errors.HttpError as e:
        print(f"❌ Erreur API YouTube : {e}")
        return []

# =========================
#  Analyse des commentaires avec Gemini
# =========================
def analyze_with_gemini(comments):
    if not comments:
        return "❌ Aucun commentaire disponible pour analyser la vidéo."

    # On limite à 50 commentaires pour éviter une surcharge
    sample = comments[:50]

    model = genai.GenerativeModel("gemini-2.5-pro")

    prompt = f"""
    Voici une liste de commentaires d'une vidéo YouTube :

    {sample}

    ➡️ Analyse ces retours et réponds clairement :
    1. La vidéo est-elle pertinente ou non ? (Oui / Non)
    2. Pour quel type de spectateurs ?
    3. Donne une note de pertinence sur 10
    4. Fais un résumé rapide de l'avis général
    """

    response = model.generate_content(prompt)
    return response.text

# =========================
#  Fonction principale : évaluation d'une vidéo
# =========================
def evaluate_youtube_video(video_id):
    comments = get_video_comments(YOUTUBE_API_KEY, video_id)
    result = analyze_with_gemini(comments)
    return result

# =========================
# 🎬 Exécution
# =========================
if __name__ == "__main__":
    youtube_url = input("Collez le lien de la vidéo YouTube : ").strip()

    video_id = extract_video_id(youtube_url)

    if not video_id:
        print("❌ Impossible d'extraire l'ID de la vidéo. Vérifiez le lien.")
    else:
        analysis = evaluate_youtube_video(video_id)
        print("\n=== Résultat de l'analyse ===\n")
        print(analysis)